import { Menu, Navside } from '@/components/navside/Navside'
import { Icon } from '@reusable-ui/components'
import Head from 'next/head'



export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navside theme='primary' size='lg'>
                    <Menu>
                        <Icon icon='dashboard' /> Dashboard
                    </Menu>
                    <Menu>
                        <Icon icon='inventory' /> Stock
                    </Menu>
                    <Menu active={true}>
                        <Icon icon='fact_check' /> Requests
                    </Menu>
                    <Menu>
                        <Icon icon='shield' /> Risk
                    </Menu>
                    <Menu>
                        <Icon icon='analytics' /> Analitics
                    </Menu>
                    <Menu>
                        <Icon icon='menu_book' /> Regulations
                    </Menu>
                    <Menu>
                        <Icon icon='widgets' /> Widgets
                    </Menu>
                </Navside>
            </main>
        </>
    )
}
