import { useState } from 'react'
import Head from 'next/head'

import { Navside, Menu } from '@/components/navside'
import { Icon } from '@reusable-ui/components'



export default function Home() {
    // states:
    const [activeMenu, setActiveMenu] = useState<string>('dashboard');
    
    
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navside theme='primary' size='lg'>
                    <Menu actionCtrl={false}>
                        My Logo
                    </Menu>
                    <Menu active={activeMenu === 'dashboard'} onClick={() => setActiveMenu('dashboard')}>
                        <Icon icon='dashboard' /> Dashboard
                    </Menu>
                    <Menu active={activeMenu === 'stock'} onClick={() => setActiveMenu('stock')}>
                        <Icon icon='inventory' /> Stock
                    </Menu>
                    <Menu active={activeMenu === 'requests'} onClick={() => setActiveMenu('requests')}>
                        <Icon icon='fact_check' /> Requests
                    </Menu>
                    <Menu active={activeMenu === 'risk'} onClick={() => setActiveMenu('risk')}>
                        <Icon icon='shield' /> Risk
                    </Menu>
                    <Menu active={activeMenu === 'analitics'} onClick={() => setActiveMenu('analitics')}>
                        <Icon icon='analytics' /> Analitics
                    </Menu>
                    <Menu active={activeMenu === 'regulations'} onClick={() => setActiveMenu('regulations')}>
                        <Icon icon='menu_book' /> Regulations
                    </Menu>
                    <Menu active={activeMenu === 'widgets'} onClick={() => setActiveMenu('widgets')}>
                        <Icon icon='widgets' /> Widgets
                    </Menu>
                </Navside>
            </main>
        </>
    )
}
